config/routes.rb
Rails.application.routes.draw do
  resources :customer_requests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer_request.rb
class CustomerRequest < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customer_requests_controller.rb
class CustomerRequestsController < ApplicationController
  before_action :set_customer_request, only: [:show, :edit, :update, :destroy]

  # GET /customer_requests
  # GET /customer_requests.json
  def index
    @customer_requests = CustomerRequest.all
  end

  # GET /customer_requests/1
  # GET /customer_requests/1.json
  def show
  end

  # GET /customer_requests/new
  def new
    @customer_request = CustomerRequest.new
  end

  # GET /customer_requests/1/edit
  def edit
  end

  # POST /customer_requests
  # POST /customer_requests.json
  def create
    @customer_request = CustomerRequest.new(customer_request_params)

    respond_to do |format|
      if @customer_request.save
        format.html { redirect_to @customer_request, notice: 'Customer request was successfully created.' }
        format.json { render :show, status: :created, location: @customer_request }
      else
        format.html { render :new }
        format.json { render json: @customer_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_requests/1
  # PATCH/PUT /customer_requests/1.json
  def update
    respond_to do |format|
      if @customer_request.update(customer_request_params)
        format.html { redirect_to @customer_request, notice: 'Customer request was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_request }
      else
        format.html { render :edit }
        format.json { render json: @customer_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_requests/1
  # DELETE /customer_requests/1.json
  def destroy
    @customer_request.destroy
    respond_to do |format|
      format.html { redirect_to customer_requests_url, notice: 'Customer request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_request
      @customer_request = CustomerRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_request_params
      params.require(:customer_request).permit(:customer_name, :customer_phone, :brand, :notes, :status, :deposit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def human_boolean(boolean)
        boolean ? 'Yes' : 'No'
    end
end

app/helpers/customer_requests_helper.rb
module CustomerRequestsHelper
    
end

app/views/customer_requests/_form.html.erb
<%= form_with(model: customer_request, local: true) do |form| %>
  <% if customer_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_request.errors.count, "error") %> prohibited this customer_request from being saved:</h2>

      <ul>
      <% customer_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= form.label :Customer_Name %>
    <%= form.text_field :customer_name, id: :customer_request_customer_name, class: 'form-control', placeholder: 'Customer Name' %>
  </div>

  <div class="control-group">
    <%= form.label :customer_phone %>
    <%= form.text_field :customer_phone, id: :customer_request_customer_phone, class: 'form-control', autofocus: true, placeholder: 'xxx-xxx-xxxx' %>
  </div>

  <div class="control-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :customer_request_brand, class: 'form-control', placeholder: 'Geox' %>
  </div>

  <div class="control-group">
    <%= form.label :notes %>
    <%= form.text_field :notes, id: :customer_request_notes, class: 'form-control', placeholder: 'Size, Color, Quntity' %>
  </div>

  <div class="control-group">
    <%= form.label :status %>
    <%= form.select(:status, options_for_select(['Pennding', 'Ordered', 'Called']), {}, class: 'form-control') %>
  </div>

  <div class="control-group">
    <%= form.label :deposit %>
    <%= form.check_box :deposit, id: :customer_request_deposit, class: 'form-control float-left' %>
  </div>
<hr />
  <div class="control-group">
    <%= form.submit 'Add a new request', :class => 'btn btn-success float-left kkw__submit-btn' %>
  </div>
<% end %>

app/views/customer_requests/edit.html.erb
<h1>Editing Customer Request</h1>

<%= render 'form', customer_request: @customer_request %>

<%= link_to 'Show', @customer_request, class: 'btn-primary btn' %> |
<%= link_to 'Home', customer_requests_path, class: 'btn btn-info' %>

app/views/customer_requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col"><h3>Kiddie Kobbler Westboro <small class="text-muted"> Customer Requests</small></h3></div>
<div class="col"><%= link_to 'New Customer Request', new_customer_request_path, class: 'float-right btn-sm btn-success' %></div>
</div>



<ul class="list-group">
  <li class="list-group-item active row kkw__list-heading">
    <div class="col col-sm-1">Date</div>
    <div class="col col-md-2">Customer Name</div>
    <div class="col col-md-2">Customer Phone</div>
    <div class="col col-md-1">Brand</div>
    <div class="col col-md-4">Notes</div>
    <div class="col col-md-1">Status</div>
    <div class="col col-md-1">Deposit</div>
  </li>
  <% @customer_requests.each do |customer_request| %>
  <li class="list-group-item row kkw__list-list">
  <div class="col col-md-1"><%= customer_request.created_at.strftime('%b. %d') %></div>
  <div class="col col-md-2"><%= customer_request.customer_name %></div>
  <div class="col col-md-2"><%= customer_request.customer_phone %></div>
  <div class="col col-md-1"><%= customer_request.brand %></div>
  <div class="col col-md-4 kkw__note-view"><%= customer_request.notes %></div>
  <div class="col col-md-1"><%= customer_request.status %></div>
  <div class="col col-md-1"><%= customer_request.deposit.to_yesno %></div>
  <a href="#" class="kkw__tools-showHide">
  <div class="kkw__tools"><%= link_to 'Show', customer_request, class: 'btn-primary btn-sm' %> | <%= link_to 'Edit', edit_customer_request_path(customer_request), class: ' btn-sm btn-warning' %> | <%= link_to 'Destroy', customer_request, method: :delete, data: { confirm: 'Are you sure?' }, class: ' btn-sm btn-danger' %></div></a>
  </li>
  <% end %>
<ul>

app/views/customer_requests/new.html.erb
<h1>New Customer Request</h1>

<%= render 'form', customer_request: @customer_request %>

<%= link_to 'Home', customer_requests_path, class: 'btn btn-info' %>

app/views/customer_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @customer_request.customer_name %>
</p>

<p>
  <strong>Customer phone:</strong>
  <%= @customer_request.customer_phone %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @customer_request.brand %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer_request.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @customer_request.status %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @customer_request.deposit %>
</p>

<%= link_to 'Edit', edit_customer_request_path(@customer_request), :class => 'btn btn-primary' %> |
<%= link_to 'Home', customer_requests_path, :class => 'btn btn-info' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customer Requests</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <%= yield %>
  </div>
  </body>
</html>